name: portfolio
description: A simple portfolio about myself after working 5 months in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0 #font
  flutter_svg: ^1.1.1+1 #svg
  flutter_riverpod: ^1.0.4 #state management
  flutter_staggered_grid_view: 0.6.2 #staggedGrid
  url_launcher: ^6.3.2 #URLauncher
  scroll_to_index: ^3.0.1 #scrollToIndex
  http: ^1.0.0 #httpclient
  toastification: ^3.0.3
  animated_text_kit: ^4.3.0
  visibility_detector: ^0.4.0+2
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  animated_background: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/
    - assets/projects/
    - assets/skills/

  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
