name: portfolio
description: A simple portfolio about myself after working 2 months in flutter.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0 #font
  flutter_svg: ^1.1.1+1 #svg
  flutter_riverpod: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.3.2
  scroll_to_index: ^3.0.1
  http: ^1.0.0
  toastification: ^3.0.3
  animated_text_kit: ^4.3.0
  visibility_detector: ^0.4.0+2
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  animated_background: ^2.0.0
  m3_carousel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/
    - assets/projects/
    - assets/skills/

  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
